tunnel: vetapi-khmersoftware
credentials-file: /etc/cloudflared/vetapi-khmersoftware.json

ingress:
  - hostname: vetapi.khmersoftware.com
    service: http://nginx:80
  - hostname: dev.khmersoftware.com
    service: http://nginx:80
  - service: http_status:404
